import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'doc',
      id: 'index',
    },
    {
      type: 'category',
      label: 'Tutorial',
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorial',
        },
      ],
    },
    {
      type: 'category',
      label: 'Fixtures',
      items: [
        {
          type: 'autogenerated',
          dirName: 'fixtures',
        },
      ],
    },
    {
      type: 'category',
      label: 'API',
      items: [
        {
          type: 'autogenerated',
          dirName: 'api',
        },
      ],
    },
    {
      type: 'doc',
      id: 'demo',
    },
    {
      type: 'doc',
      id: 'limitations',
    },
  ],
  publicApi: [
    {
      type: 'autogenerated',
      dirName: 'public-api',
    },
  ],
};

export default sidebars;
